name: "Install Verilator Action"
description: "Install Verilator for use in a Github Action workflow, with caching"
inputs:
  version:
    description: 'Version to check out (i.e. "stable" or "master" or "v4.210")'
    required: true
    default: 'stable'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git help2man perl python3 make autoconf g++ flex bison ccache
        sudo apt-get install -y libfl2 libfl-dev

    - name: Cache Verilator
      id: cache-verilator
      uses: actions/cache@v2
      with:
        path: ~/verilator
        key: ${{ runner.os }}-verilator-${{ inputs.version }}-${{ hashFiles('**/verilator/**') }}

    - name: Checkout Verilator
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        git clone https://github.com/verilator/verilator ~/verilator
        cd ~/verilator
        git checkout $INPUT_VERSION

    - name: Build Verilator
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ~/verilator
        autoconf
        ./configure
        make -j $(nproc)
        sudo make install

    - name: Use cached Verilator
      if: steps.cache-verilator.outputs.cache-hit == 'true'
      shell: bash
      run: |
        cd ~/verilator
        sudo make install
