name: "Install Verilator Action"
description: "Install Verilator for use in a Github Action workflow"
inputs:
  version:
    description: 'Version to check out (i.e. "stable" or "master" or "v4.210")'
    required: true
    default: 'stable'
runs:
  using: 'composite'
  steps:
    # Script based on: https://github.com/verilator/verilator/blob/master/docs/guide/install.rst#id3
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install git help2man perl python3 make autoconf g++ flex bison ccache
        # sudo apt-get install libgoogle-perftools-dev numactl perl-doc (gives error when installing 'libgoogle-perftools-dev': https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1991919)
        sudo apt-get install libfl2  # Ubuntu only (ignore if gives error)
        sudo apt-get install libfl-dev  # Ubuntu only (ignore if gives error)
        # sudo apt-get install zlibc zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error); skipping because it leads to 'Unable to locate package zlibc' error
    - name: Checkout Verilator
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        git clone https://github.com/verilator/verilator   # Only first time
        cd verilator
        git pull         # Make sure git repository is up-to-date
        git checkout $INPUT_VERSION
    - name: Build Verilator
      shell: bash
      run: |
        cd verilator
        autoconf         # Create ./configure script
        ./configure      # Configure and create Makefile
        make -j `nproc`  # Build Verilator itself (if error, try just 'make')
        sudo make install
