name: Testing Verilator installation

on:
    push:
      branches:
        - main
      paths:
        - action.yml
        - .github/workflows/test.yml
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: v0xnihili/install-verilator-action@main
    - run: verilator --version
